services:
  backend:
    container_name: backend
    restart: unless-stopped
    image: backend
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 8000:8000
    environment:
      - API_HOST=0.0.0.0
      - DB_URL=postgres://suscord:suscord@postgres:5432/suscord?sslmode=disable
      - MIGRATE=true
    networks:
      - suscord

  postgres:
    container_name: postgres
    image: postgres:17-alpine
    environment:
      - POSTGRES_DB=suscord
      - POSTGRES_USER=suscord
      - POSTGRES_PASSWORD=suscord
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U suscord -d suscord"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - suscord

  livekit:
    image: livekit/livekit-server:latest
    restart: unless-stopped
    container_name: livekit
    command: --config /etc/livekit.yaml
    ports:
      - "7880:7880"
      - "7881:7881"
      - "50000-50100:50000-50100/udp"
    volumes:
      - ./livekit/config.yaml:/etc/livekit.yaml
    networks:
      - suscord

volumes:
  postgres_data:

networks:
  suscord:
    driver: bridge
